### ISSUE TITLE
[BUG] Filtering introduces duplicate cards

### ISSUE THREAD

**Issue by hemidactylus** [datastaxdevs/datastax-content-repository#2]
Reproduce: open the sample app gallery and select "workshops" filter. The first three workshop items appear twice, as two consecutive cards, with _almost_ the same properties except, sometimes, for an added tag in one of the two.

Look at the picture:
~the first card features a "workshop" tag (first in the sequence), the second doesn't.~ Edit: no, just reshuffled.
The third card has "cassandra" (first in sequence), the fourth doesn't. (+ reshuffled)
The fifth has "ai", the sixth doesn't.

From that point onward, no duplication occurs.
![duplicates](https://user-images.githubusercontent.com/14221764/217862794-06e5e0d7-a4e1-4348-9309-2e044ec565ba.png)

**Comment by hemidactylus** [comment]
I stand corrected: I see other duplicates if I scroll down: for instance, there's two Battlestax pointing to the same github.

**Comment by synedra** [comment]
Fixed!
